package golang

import (
	"bytes"
	"strings"
	"text/template"
)

// DockerfileTemplate is the template for generating Go Dockerfiles.
// Uses multi-stage build with distroless for minimal production image.
const DockerfileTemplate = `# syntax=docker/dockerfile:1.4
# Generated by cbox - Do not edit directly

# ============================================
# Stage 1: Build
# ============================================
FROM golang:{{.GoVersion}}-alpine AS builder

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache git ca-certificates tzdata

# Copy go mod files first for better caching
COPY go.mod go.sum* ./

# Download dependencies
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

# Copy source code
COPY . .

# Build the binary
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags="-w -s" \
    -o /app/{{.BinaryName}} {{.EntryPoint}}

# ============================================
# Stage 2: Production
# ============================================
FROM gcr.io/distroless/static-debian12 AS production

WORKDIR /

# Copy binary from builder
COPY --from=builder /app/{{.BinaryName}} /{{.BinaryName}}

# Copy timezone data and CA certificates
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Run as non-root
USER nonroot:nonroot

EXPOSE {{.Port}}

ENTRYPOINT ["/{{.BinaryName}}"]
`

// DevDockerfileTemplate is optimized for development with hot reload.
const DevDockerfileTemplate = `# syntax=docker/dockerfile:1.4
# Generated by cbox for development

FROM golang:{{.GoVersion}}-alpine

WORKDIR /app

# Install development dependencies
RUN apk add --no-cache git ca-certificates tzdata

# Install air for hot reloading
RUN go install github.com/air-verse/air@latest

# Copy go mod files first for better caching
COPY go.mod go.sum* ./

# Download dependencies
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

# Create air config if it doesn't exist
RUN echo 'root = "."' > /tmp/.air.toml && \
    echo 'tmp_dir = "tmp"' >> /tmp/.air.toml && \
    echo '[build]' >> /tmp/.air.toml && \
    echo '  cmd = "go build -o ./tmp/main {{.EntryPoint}}"' >> /tmp/.air.toml && \
    echo '  bin = "./tmp/main"' >> /tmp/.air.toml && \
    echo '  include_ext = ["go", "tpl", "tmpl", "html"]' >> /tmp/.air.toml && \
    echo '  exclude_dir = ["assets", "tmp", "vendor", "node_modules"]' >> /tmp/.air.toml && \
    echo '  delay = 1000' >> /tmp/.air.toml && \
    echo '[log]' >> /tmp/.air.toml && \
    echo '  time = false' >> /tmp/.air.toml && \
    echo '[misc]' >> /tmp/.air.toml && \
    echo '  clean_on_exit = true' >> /tmp/.air.toml

# Source will be mounted as volume in dev mode
# COPY . .

EXPOSE {{.Port}}

CMD ["air", "-c", "/tmp/.air.toml"]
`

// TemplateData contains all data needed to render a Dockerfile.
type TemplateData struct {
	GoVersion  string
	BinaryName string
	EntryPoint string
	Port       int
}

// GenerateDockerfile creates a production Dockerfile from project info.
func GenerateDockerfile(project *Project, port int) (string, error) {
	data := buildTemplateData(project, port)
	return renderTemplate(DockerfileTemplate, data)
}

// GenerateDevDockerfile creates a development Dockerfile from project info.
func GenerateDevDockerfile(project *Project, port int) (string, error) {
	data := buildTemplateData(project, port)
	return renderTemplate(DevDockerfileTemplate, data)
}

func buildTemplateData(project *Project, port int) TemplateData {
	if port == 0 {
		port = project.GetDefaultPort()
	}

	entryPoint := project.EntryPoint
	if entryPoint == "" {
		entryPoint = "."
	}

	return TemplateData{
		GoVersion:  project.GoVersion,
		BinaryName: project.BinaryName,
		EntryPoint: entryPoint,
		Port:       port,
	}
}

func renderTemplate(tmplStr string, data TemplateData) (string, error) {
	tmpl, err := template.New("dockerfile").Parse(tmplStr)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// GenerateDockerignore creates a .dockerignore file content.
func GenerateDockerignore(project *Project) string {
	lines := []string{
		"# Generated by cbox",
		".git",
		".gitignore",
		".cbox",
		"*.log",
		".env",
		".env.*",
		"!.env.example",
		"",
		"# Go specific",
		"*.exe",
		"*.exe~",
		"*.dll",
		"*.so",
		"*.dylib",
		"*.test",
		"*.out",
		"go.work",
		"",
		"# Build artifacts",
		"bin/",
		"dist/",
		"tmp/",
		"",
		"# IDE",
		".idea/",
		".vscode/",
		"*.swp",
		"*.swo",
	}

	// Don't ignore vendor if using vendored deps
	if !project.HasVendor {
		lines = append(lines, "vendor/")
	}

	return strings.Join(lines, "\n") + "\n"
}
