package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/bobbyrathore/cbox/internal/builder/nodejs"
	"github.com/bobbyrathore/cbox/internal/config"
	"github.com/bobbyrathore/cbox/internal/output"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var initForce bool

var initCmd = &cobra.Command{
	Use:   "init [path]",
	Short: "Initialize a new cbox project",
	Long: `Initialize a new cbox project by detecting the project type
and generating a cbox.yaml configuration file.

Examples:
  cbox init           Initialize in current directory
  cbox init ./myapp   Initialize in specified directory`,
	Args: cobra.MaximumNArgs(1),
	RunE: runInit,
}

func init() {
	initCmd.Flags().BoolVar(&initForce, "force", false, "overwrite existing cbox.yaml")
}

func runInit(cmd *cobra.Command, args []string) error {
	console := output.NewWithOptions(verbose, quiet)

	path := "."
	if len(args) > 0 {
		path = args[0]
	}

	// Get absolute path
	absPath, err := filepath.Abs(path)
	if err != nil {
		return fmt.Errorf("invalid path: %w", err)
	}

	// Check if cbox.yaml already exists
	configPath := filepath.Join(absPath, "cbox.yaml")
	if _, err := os.Stat(configPath); err == nil && !initForce {
		console.Error("cbox.yaml already exists")
		console.Info("Use --force to overwrite")
		return fmt.Errorf("config already exists")
	}

	console.Info("Detecting project type...")

	// Detect project type
	cfg := config.DefaultConfig(absPath)
	detected := false

	// Check for Node.js
	if nodejs.IsProject(absPath) {
		project, err := nodejs.Detect(absPath)
		if err == nil {
			detected = true
			detectedInfo := fmt.Sprintf("Node.js (%s", project.PackageManager)
			if project.HasTypeScript {
				detectedInfo += ", TypeScript"
			}
			if project.Framework != "" {
				detectedInfo += ", " + string(project.Framework)
			}
			detectedInfo += ")"
			console.Success("Detected: %s", detectedInfo)

			// Create service config
			svc := config.Service{
				Path:    ".",
				Runtime: "nodejs",
				Port:    project.GetDefaultPort(),
				Command: project.GetStartCommand(),
				Dev: config.DevConfig{
					Command: project.GetDevCommand(),
					Sync:    true,
					Watch: config.WatchConfig{
						Paths:  []string{"src/", "package.json"},
						Ignore: []string{"node_modules/", "dist/", ".next/"},
					},
				},
				Env: map[string]string{
					"NODE_ENV": "production",
				},
			}

			cfg.Services["app"] = svc
		}
	}

	// Check for Go
	if !detected {
		if _, err := os.Stat(filepath.Join(absPath, "go.mod")); err == nil {
			detected = true
			console.Success("Detected: Go")

			cfg.Services["app"] = config.Service{
				Path:    ".",
				Runtime: "go",
				Port:    8080,
				Command: []string{"./app"},
				Dev: config.DevConfig{
					Command: []string{"go", "run", "."},
					Watch: config.WatchConfig{
						Paths:  []string{"."},
						Ignore: []string{"vendor/"},
					},
				},
			}
		}
	}

	// Check for Python
	if !detected {
		for _, pyfile := range []string{"requirements.txt", "pyproject.toml", "setup.py"} {
			if _, err := os.Stat(filepath.Join(absPath, pyfile)); err == nil {
				detected = true
				console.Success("Detected: Python")

				cfg.Services["app"] = config.Service{
					Path:    ".",
					Runtime: "python",
					Port:    8000,
					Command: []string{"python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0"},
					Dev: config.DevConfig{
						Command: []string{"python", "-m", "uvicorn", "main:app", "--reload", "--host", "0.0.0.0"},
						Watch: config.WatchConfig{
							Paths:  []string{"."},
							Ignore: []string{"__pycache__/", ".venv/", "venv/"},
						},
					},
				}
				break
			}
		}
	}

	if !detected {
		console.Warn("Could not detect project type")
		console.Info("Creating minimal cbox.yaml - please edit manually")

		// Create a template config
		cfg.Services["app"] = config.Service{
			Path:    ".",
			Runtime: "nodejs", // Default
			Port:    3000,
			Command: []string{"npm", "start"},
			Dev: config.DevConfig{
				Command: []string{"npm", "run", "dev"},
			},
		}
	}

	// Generate cbox.yaml
	yamlBytes, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("failed to generate config: %w", err)
	}

	// Add header comment
	content := "# cbox.yaml - Generated by cbox init\n# See https://github.com/bobbyrathore/cbox for documentation\n\n" + string(yamlBytes)

	// Write file
	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	console.Success("Created cbox.yaml")

	// Generate .dockerignore if it doesn't exist
	dockerignorePath := filepath.Join(absPath, ".dockerignore")
	if _, err := os.Stat(dockerignorePath); os.IsNotExist(err) {
		// Get the detected runtime from the service config
		runtime := ""
		if svc, ok := cfg.Services["app"]; ok {
			runtime = svc.Runtime
		}

		dockerignoreContent := getDockerignoreContent(runtime)
		if err := os.WriteFile(dockerignorePath, []byte(dockerignoreContent), 0644); err != nil {
			console.Warn("Failed to create .dockerignore: %v", err)
		} else {
			console.Success("Created .dockerignore")
		}
	}

	console.Newline()
	console.Info("Next steps:")
	console.Info("  1. Review and customize cbox.yaml")
	console.Info("  2. Run 'cbox dev' to start development")
	console.Info("  3. Run 'cbox up' to start all services")

	return nil
}

// getDockerignoreContent returns the appropriate .dockerignore content based on runtime
func getDockerignoreContent(runtime string) string {
	// Common ignores for all runtimes
	common := `# Git
.git/
.gitignore

# Docker
.dockerignore
Dockerfile*
docker-compose*

# IDE and OS
.DS_Store
.idea/
.vscode/
*.swp
*.swo

# Logs
*.log

# Environment files
.env
.env.*
!.env.example

# Documentation
*.md
!README.md
`

	switch runtime {
	case "nodejs":
		return common + `
# Node.js specific
node_modules/
npm-debug.log
.npm/
dist/
.next/
coverage/
.nyc_output/
`
	case "python":
		return common + `
# Python specific
__pycache__/
*.py[cod]
*$py.class
.venv/
venv/
.pytest_cache/
.coverage
htmlcov/
.tox/
.eggs/
*.egg-info/
`
	case "go":
		return common + `
# Go specific
vendor/
*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out
`
	default:
		return common
	}
}
