package nodejs

import (
	"bytes"
	"strings"
	"text/template"
)

// DockerfileTemplate is the template for generating Node.js Dockerfiles.
const DockerfileTemplate = `# syntax=docker/dockerfile:1.4
# Generated by cbox - Do not edit directly

# ============================================
# Stage 1: Dependencies
# ============================================
FROM node:{{.NodeVersion}}-slim AS deps

WORKDIR /app

# Install additional tools if needed
{{- if eq .PackageManager "pnpm"}}
RUN corepack enable pnpm
{{- end}}
{{- if and (eq .PackageManager "yarn") .YarnBerry}}
RUN corepack enable
{{- end}}

# Copy package files first (better layer caching)
COPY package.json {{.LockfileName}} ./
{{- if and (eq .PackageManager "yarn") .YarnBerry}}
COPY .yarnrc.yml ./
{{- if .HasYarnPlugins}}
COPY .yarn .yarn
{{- end}}
{{- end}}

# Install dependencies with cache mount
RUN --mount=type=cache,target={{.CacheDirectory}} \
    {{.InstallCommand}}

# ============================================
# Stage 2: Build
# ============================================
FROM deps AS build

# Copy source code
COPY . .

{{- if .HasBuildStep}}

# Build the application
RUN {{.BuildCommand}}
{{- end}}

# ============================================
# Stage 3: Production
# ============================================
FROM node:{{.NodeVersion}}-slim AS production

WORKDIR /app

{{- if eq .PackageManager "pnpm"}}
RUN corepack enable pnpm
{{- end}}

# Copy package files
COPY package.json {{.LockfileName}} ./
{{- if and (eq .PackageManager "yarn") .YarnBerry}}
COPY .yarnrc.yml ./
{{- end}}

# Install production dependencies only
RUN --mount=type=cache,target={{.CacheDirectory}} \
    {{.InstallProdCommand}}

{{- if .HasBuildStep}}

# Copy built files
COPY --from=build /app/{{.OutputDir}} ./{{.OutputDir}}
{{- else}}

# Copy source files
COPY --from=build /app .
{{- end}}

# Run as non-root user
USER node

EXPOSE {{.Port}}

CMD {{.StartCommand}}
`

// DevDockerfileTemplate is optimized for development with bind mounts.
const DevDockerfileTemplate = `# syntax=docker/dockerfile:1.4
# Generated by cbox for development

FROM node:{{.NodeVersion}}-slim

WORKDIR /app

{{- if eq .PackageManager "pnpm"}}
RUN corepack enable pnpm
{{- end}}
{{- if and (eq .PackageManager "yarn") .YarnBerry}}
RUN corepack enable
{{- end}}

# Install nodemon globally for file watching (if not using framework HMR)
{{- if not .HasFrameworkHMR}}
RUN npm install -g nodemon
{{- end}}

# Copy package files
COPY package.json {{.LockfileName}} ./
{{- if and (eq .PackageManager "yarn") .YarnBerry}}
COPY .yarnrc.yml ./
{{- if .HasYarnPlugins}}
COPY .yarn .yarn
{{- end}}
{{- end}}

# Install all dependencies (including devDependencies)
RUN --mount=type=cache,target={{.CacheDirectory}} \
    {{.InstallCommand}}

# Source will be mounted as volume in dev mode
# COPY . .

EXPOSE {{.Port}}

CMD {{.DevCommand}}
`

// TemplateData contains all data needed to render a Dockerfile.
type TemplateData struct {
	NodeVersion       string
	PackageManager    string
	LockfileName      string
	YarnBerry         bool
	HasYarnPlugins    bool
	CacheDirectory    string
	InstallCommand    string
	InstallProdCommand string
	HasBuildStep      bool
	BuildCommand      string
	OutputDir         string
	Port              int
	StartCommand      string
	DevCommand        string
	HasFrameworkHMR   bool
}

// GenerateDockerfile creates a production Dockerfile from project info.
func GenerateDockerfile(project *Project, port int) (string, error) {
	data := buildTemplateData(project, port, false)
	return renderTemplate(DockerfileTemplate, data)
}

// GenerateDevDockerfile creates a development Dockerfile from project info.
func GenerateDevDockerfile(project *Project, port int) (string, error) {
	data := buildTemplateData(project, port, true)
	return renderTemplate(DevDockerfileTemplate, data)
}

func buildTemplateData(project *Project, port int, isDev bool) TemplateData {
	if port == 0 {
		port = project.GetDefaultPort()
	}

	installCmd := strings.Join(project.GetInstallCommand(), " ")

	// Production install command (no dev dependencies)
	prodInstallCmd := installCmd
	switch project.PackageManager {
	case NPM:
		prodInstallCmd = "npm ci --omit=dev"
	case Yarn:
		if project.YarnBerry {
			prodInstallCmd = "yarn workspaces focus --production"
		} else {
			prodInstallCmd = "yarn install --frozen-lockfile --production"
		}
	case Pnpm:
		prodInstallCmd = "pnpm install --frozen-lockfile --prod"
	case Bun:
		prodInstallCmd = "bun install --frozen-lockfile --production"
	}

	buildCmd := ""
	if project.HasBuildStep {
		buildCmd = strings.Join(project.GetBuildCommand(), " ")
	}

	startCmd := formatCmdForDockerfile(project.GetStartCommand())
	devCmd := formatCmdForDockerfile(project.GetDevCommand())

	// Check if framework has built-in HMR
	hasHMR := project.Framework == FrameworkNext ||
		project.Framework == FrameworkVite ||
		project.Framework == FrameworkRemix ||
		project.Framework == FrameworkAstro

	return TemplateData{
		NodeVersion:        project.NodeVersion,
		PackageManager:     string(project.PackageManager),
		LockfileName:       project.GetLockfileName(),
		YarnBerry:          project.YarnBerry,
		HasYarnPlugins:     false, // TODO: detect .yarn/plugins
		CacheDirectory:     project.GetCacheDirectory(),
		InstallCommand:     installCmd,
		InstallProdCommand: prodInstallCmd,
		HasBuildStep:       project.HasBuildStep,
		BuildCommand:       buildCmd,
		OutputDir:          project.OutputDir,
		Port:               port,
		StartCommand:       startCmd,
		DevCommand:         devCmd,
		HasFrameworkHMR:    hasHMR,
	}
}

func formatCmdForDockerfile(cmd []string) string {
	// Format as JSON array for CMD
	parts := make([]string, len(cmd))
	for i, c := range cmd {
		parts[i] = `"` + c + `"`
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func renderTemplate(tmplStr string, data TemplateData) (string, error) {
	tmpl, err := template.New("dockerfile").Parse(tmplStr)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// GenerateDockerignore creates a .dockerignore file content.
func GenerateDockerignore(project *Project) string {
	lines := []string{
		"# Generated by cbox",
		"node_modules",
		".git",
		".gitignore",
		".cbox",
		"*.log",
		"npm-debug.log*",
		"yarn-debug.log*",
		"yarn-error.log*",
		".env",
		".env.*",
		"!.env.example",
		"coverage",
		".nyc_output",
		"*.test.ts",
		"*.test.js",
		"*.spec.ts",
		"*.spec.js",
		"__tests__",
		"test",
		"tests",
	}

	// Framework-specific ignores
	switch project.Framework {
	case FrameworkNext:
		lines = append(lines, ".next", "out")
	case FrameworkVite:
		lines = append(lines, "dist")
	case FrameworkRemix:
		lines = append(lines, "build", ".cache")
	}

	// Add output directory if it exists
	if project.OutputDir != "" {
		// Only add if not already in list
		found := false
		for _, l := range lines {
			if l == project.OutputDir {
				found = true
				break
			}
		}
		if !found {
			lines = append(lines, project.OutputDir)
		}
	}

	return strings.Join(lines, "\n") + "\n"
}
