package python

import (
	"bytes"
	"strings"
	"text/template"
)

// DockerfileTemplate is the template for generating Python Dockerfiles.
const DockerfileTemplate = `# syntax=docker/dockerfile:1.4
# Generated by cbox - Do not edit directly

# ============================================
# Stage 1: Dependencies
# ============================================
FROM python:{{.PythonVersion}}-slim AS deps

WORKDIR /app

# Install build dependencies and wget for health checks
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

{{- if eq .PackageManager "poetry"}}
# Install Poetry
RUN pip install --no-cache-dir poetry && poetry config virtualenvs.create false
COPY pyproject.toml poetry.lock* ./
{{- else if eq .PackageManager "pipenv"}}
# Install Pipenv
RUN pip install --no-cache-dir pipenv
COPY Pipfile Pipfile.lock ./
{{- else if eq .PackageManager "uv"}}
# Install uv
RUN pip install --no-cache-dir uv
COPY requirements*.txt ./
{{- else}}
COPY requirements*.txt ./
{{- end}}

# Install dependencies
RUN {{.InstallProdCommand}}

# ============================================
# Stage 2: Production
# ============================================
FROM python:{{.PythonVersion}}-slim AS production

WORKDIR /app

# Install wget for health checks
RUN apt-get update && apt-get install -y --no-install-recommends wget && rm -rf /var/lib/apt/lists/*

{{- if eq .PackageManager "poetry"}}
# Install Poetry for runtime
RUN pip install --no-cache-dir poetry && poetry config virtualenvs.create false
{{- end}}

# Copy installed packages from deps stage
COPY --from=deps /usr/local/lib/python{{.PythonVersion}}/site-packages /usr/local/lib/python{{.PythonVersion}}/site-packages
COPY --from=deps /usr/local/bin /usr/local/bin

# Copy application code
COPY . .

# Run as non-root user
RUN useradd --create-home --shell /bin/bash appuser
USER appuser

EXPOSE {{.Port}}

CMD {{.StartCommand}}
`

// DevDockerfileTemplate is optimized for development with bind mounts.
const DevDockerfileTemplate = `# syntax=docker/dockerfile:1.4
# Generated by cbox for development

FROM python:{{.PythonVersion}}-slim

WORKDIR /app

# Install development dependencies and wget for health checks
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

{{- if eq .PackageManager "poetry"}}
# Install Poetry
RUN pip install --no-cache-dir poetry && poetry config virtualenvs.create false
COPY pyproject.toml poetry.lock* ./
RUN poetry install --no-interaction --no-ansi
{{- else if eq .PackageManager "pipenv"}}
# Install Pipenv
RUN pip install --no-cache-dir pipenv
COPY Pipfile Pipfile.lock ./
RUN pipenv install --dev --deploy
{{- else if eq .PackageManager "uv"}}
# Install uv
RUN pip install --no-cache-dir uv
COPY requirements*.txt ./
RUN uv pip install --system -r requirements.txt
{{- else}}
COPY requirements*.txt ./
RUN pip install --no-cache-dir -r requirements.txt
{{- if .HasDevRequirements}}
RUN pip install --no-cache-dir -r requirements-dev.txt 2>/dev/null || true
{{- end}}
{{- end}}

# Source will be mounted as volume in dev mode
# COPY . .

EXPOSE {{.Port}}

CMD {{.DevCommand}}
`

// TemplateData contains all data needed to render a Dockerfile.
type TemplateData struct {
	PythonVersion      string
	PackageManager     string
	InstallCommand     string
	InstallProdCommand string
	Port               int
	StartCommand       string
	DevCommand         string
	HasDevRequirements bool
}

// GenerateDockerfile creates a production Dockerfile from project info.
func GenerateDockerfile(project *Project, port int) (string, error) {
	data := buildTemplateData(project, port, false)
	return renderTemplate(DockerfileTemplate, data)
}

// GenerateDevDockerfile creates a development Dockerfile from project info.
func GenerateDevDockerfile(project *Project, port int) (string, error) {
	data := buildTemplateData(project, port, true)
	return renderTemplate(DevDockerfileTemplate, data)
}

func buildTemplateData(project *Project, port int, isDev bool) TemplateData {
	if port == 0 {
		port = project.GetDefaultPort()
	}

	installCmd := strings.Join(project.GetInstallCommand(), " ")
	installProdCmd := strings.Join(project.GetInstallProdCommand(), " ")
	startCmd := formatCmdForDockerfile(project.GetStartCommand())
	devCmd := formatCmdForDockerfile(project.GetDevCommand())

	return TemplateData{
		PythonVersion:      project.PythonVersion,
		PackageManager:     string(project.PackageManager),
		InstallCommand:     installCmd,
		InstallProdCommand: installProdCmd,
		Port:               port,
		StartCommand:       startCmd,
		DevCommand:         devCmd,
		HasDevRequirements: true, // Assume there might be dev requirements
	}
}

func formatCmdForDockerfile(cmd []string) string {
	// Format as JSON array for CMD
	parts := make([]string, len(cmd))
	for i, c := range cmd {
		parts[i] = `"` + c + `"`
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func renderTemplate(tmplStr string, data TemplateData) (string, error) {
	tmpl, err := template.New("dockerfile").Parse(tmplStr)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// GenerateDockerignore creates a .dockerignore file content.
func GenerateDockerignore(project *Project) string {
	lines := []string{
		"# Generated by cbox",
		"__pycache__",
		"*.py[cod]",
		"*$py.class",
		".Python",
		"*.so",
		".git",
		".gitignore",
		".cbox",
		"*.log",
		".env",
		".env.*",
		"!.env.example",
		".venv",
		"venv",
		"ENV",
		".pytest_cache",
		".coverage",
		"htmlcov",
		".tox",
		".nox",
		".eggs",
		"*.egg-info",
		"*.egg",
		"dist",
		"build",
		".mypy_cache",
		".ruff_cache",
		"*.pyc",
	}

	// Framework-specific ignores
	switch project.Framework {
	case FrameworkDjango:
		lines = append(lines,
			"*.sqlite3",
			"db.sqlite3",
			"staticfiles",
			"mediafiles",
		)
	}

	return strings.Join(lines, "\n") + "\n"
}
